region:
  city: "Riyadh"
  country: "Saudi Arabia"
period:
  start: "2024-10-01"
  end: "2025-09-30"
air:
  parameter: "pm25"
  who_24h_guideline: 15.0
output:
  report_name: "Riyadh_AQ_2024-10_to_2025-09"